@startuml

interface Storage {
    +Path getAddressBookFilePath()
    +Optional<ReadOnlyAddressBook> readAddressBook()
    +void saveAddressBook(ReadOnlyAddressBook)
    +Optional<UserPrefs> readUserPrefs()
    +void saveUserPrefs(ReadOnlyUserPrefs)
}

interface AddressBookStorage {
    +Path getAddressBookFilePath()
    +Optional<ReadOnlyAddressBook> readAddressBook()
    +Optional<ReadOnlyAddressBook> readAddressBook(Path)
    +void saveAddressBook(ReadOnlyAddressBook)
    +void saveAddressBook(ReadOnlyAddressBook, Path)
}

interface UserPrefsStorage {
    +Path getUserPrefsFilePath()
    +Optional<UserPrefs> readUserPrefs()
    +void saveUserPrefs(ReadOnlyUserPrefs)
}

class StorageManager {
    -AddressBookStorage addressBookStorage
    -UserPrefsStorage userPrefsStorage
    +Optional<ReadOnlyAddressBook> readAddressBook()
    +void saveAddressBook(ReadOnlyAddressBook)
    +Optional<UserPrefs> readUserPrefs()
    +void saveUserPrefs(ReadOnlyUserPrefs)
}

class JsonAddressBookStorage {
    -Path filePath
    +Optional<ReadOnlyAddressBook> readAddressBook()
    +void saveAddressBook(ReadOnlyAddressBook)
}

class JsonUserPrefsStorage {
    -Path filePath
    +Optional<UserPrefs> readUserPrefs()
    +void saveUserPrefs(ReadOnlyUserPrefs)
}

Storage <|.. AddressBookStorage
Storage <|.. UserPrefsStorage
Storage <|-- StorageManager

AddressBookStorage <|.. JsonAddressBookStorage
UserPrefsStorage <|.. JsonUserPrefsStorage

StorageManager --> AddressBookStorage
StorageManager --> UserPrefsStorage

@enduml
